package demo.model.client;

import demo.model.common.DepartmentsView;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 30 16:47:57 MSK 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewClient extends ViewUsageImpl implements DepartmentsView {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewClient() {
    }

    public Float getDepartmentSalarySum(Row row) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getDepartmentSalarySum", new String[] {
                                                                         "oracle.jbo.Row" }, new Object[] { row });
        return (Float) _ret;
    }
}

