package demo.model.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 30 16:47:56 MSK 2014
// ---------------------------------------------------------------------
public interface DepartmentsView extends ViewObject {
    Float getDepartmentSalarySum(Row row);
}

