package demo.model.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 30 16:37:31 MSK 2014
// ---------------------------------------------------------------------
public interface DepartmentsViewRow extends Row {
    Integer getDepartmentId();

    void setDepartmentId(Integer value);

    String getDepartmentName();

    void setDepartmentName(String value);

    Integer getManagerId();

    void setManagerId(Integer value);

    Integer getLocationId();

    void setLocationId(Integer value);
}

